---
title: "Tweet Heatmap"
author: "Jamie Afflerbach"
date: "10/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(leaflet)
library(sf)
library(mapview)
library(ggplot2)
library(ggmap)
library(RColorBrewer)
```

Load data
```{r}
data       <- read_csv("../data/tweets_nature_categorized.csv")
```

Create a function to apply to each tweet that identifies whether there is a word in it or not. Since all dictionary words are lower case, we also turn the full_text column lowercase.

```{r}
nature_df <- data %>%
    mutate(coords = gsub("\\)|c\\(", "", geo_coordinates)) %>%
    separate(coords, c("lat", "lon"), sep = ", ") %>%
    mutate_at(c("lon", "lat"), as.numeric) 
```

# Create a heatmap from points
```{r}
area.map <- get_map("santa barbara, california", zoom = 11, maptype = "toner-lite")
area.map <- ggmap(area.map, extent="device", legend="none")
#area.map

#santa barbara
sb.map <- get_map("santa barbara, california", zoom = 13, maptype = "toner-lite")
sb.map <- ggmap(sb.map, extent="device", legend="none")
#sb.map

#montecito
montecito <- get_map("montecito, california", zoom = 13, maptype = "toner-lite")
montecito <- ggmap(montecito, extent="device", legend="none")
#montecito

#carpinteria
carpinteria <- get_map("carpinteria, california", zoom = 13, maptype = "toner-lite")
carpinteria <- ggmap(carpinteria, extent="device", legend="none")
#carpinteria

#goleta
goleta <- get_map("goleta, california", zoom = 13, maptype = "toner-lite")
goleta <- ggmap(goleta, extent = "device", legend = "none")
#goleta
```

## Plot a heat map layer: Polygons with fill colors based on
## relative frequency of events
```{r}
sb.map2 <- sb.map + stat_density2d(data = nature_df,
 aes(x=lon, y=lat, fill=log(..level..), alpha=0.9), geom="polygon", h = .005, bins = 20, n = 300)
## Define the spectral colors to fill the density contours
sb.map3 <- sb.map2 + 
  scale_fill_gradientn(colours=rev(brewer.pal(10, "Spectral"))) 
sb.map3
```


# Nature heatmap



```{r}
sb.map4 <- sb.map + stat_density2d(data = nature_df %>% filter(nature_word == 1),
 aes(x=lon, y=lat, fill=log(..level..), alpha=0.9), geom="polygon", h = .03, bins = 20, n = 300)
## Define the spectral colors to fill the density contours
sb.map5 <- sb.map4 + 
  scale_fill_gradientn(colours=rev(brewer.pal(10, "Spectral")))
sb.map5

```


## using rasterize


```{r}
nature_sp <- data %>% 
    st_as_sf(coords = c("lon", "lat")) %>%
    st_set_crs("+init=epsg:4326") %>%
  as("Spatial")
```

```{r}
library(raster)
r <- raster(xmn=-120.5, ymn=33.88, xmx=-119.5, ymx=34.6, res=0.005)

x <- rasterize(nature_sp, r, field = "id", fun='count')
```

```{r}
leaflet() %>% addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(x, opacity = 0.7) %>% 
  fitBounds(-119.8,34.3,-119.6,34.6) %>%
  setMaxBounds(-120, 33.88, -119.5, 34.6)
```


```{r}
#take the log
logx <- log(x)

leaflet() %>% addProviderTiles(providers$CartoDB.Positron) %>%
  addRasterImage(logx, opacity = 0.7) %>% 
  fitBounds(-119.8,34.3,-119.6,34.6) %>%
  setMaxBounds(-120, 33.88, -119.5, 34.6)
```

##using hexes



```{r}
sb.map.hex <- sb.map + 
  stat_bin_hex(data = nature_df,
           aes(x = lon, y = lat), bins = 30, alpha = 0.75)


  stat_density2d(data = nature_df %>% filter(nature_word == 1),
 aes(x=lon, y=lat, fill=log(..level..), alpha=0.9), geom="polygon", h = .03, bins = 20, n = 300)
```







